.\" This man page for agentless
.TH agentless "1" "2021-03-20" "agentless 01.01" "User Commands"
.SH NAME
agentless
.SH SYNOPSIS
.B agentless - This tool can help you scan the network
.br
.B agentless [--verbose] - verbose mode
.br
.SH DESCRIPTION
This tool can help you scan the network
.SH AUTHORS
Castellani Davide: owner