.\" This man page for agentless
.TH agentless "1" "2021-03-23" "agentless 01.01" "User Commands"
.SH NAME
agentless
.SH SYNOPSIS
.B agentless - This tool can help you scan the network
.br
.B agentless [--help | -h] - help istructions
.br
.B agentless [--verbose] - verbose mode
.br
.B adresses [--adresses=...] - Choose adresses, you can use this multiple time (Replace "..." with the value(s))
.br
.B vtools [--csv] - enable csv output
.br
.B vtools [--single] - disanable multitreading
.br
.B vtools [--url=... --token=... --table=...] - enable the upload to HarperDB (Replace "..." with the value(s))
.br
.SH DESCRIPTION
This tool can help you scan the network
.SH AUTHORS
Castellani Davide: owner